services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: car
    ports:  
      - "3002:3002"
    volumes:
      - ./:/home/node/app/
    environment:
      - TZ=America/Sao_Paulo